version: '3'

services:
  django:
    build:
      context: ./backend
      dockerfile: ./docker-compose/django/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: hungry_django
    platform: linux/x86_64
    volumes:
      - ./backend:/app:z
    environment:
      - COLUMNS
    env_file:
      - ./backend/.envs/.django
      - ./backend/.envs/.overrides
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hbpostgres
      - POSTGRES_PASSWORD=hbpostgres
      - POSTGRES_DB=hbdb
