# Generated by Django 4.1.5 on 2023-01-30 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("inventories", models.ManyToManyField(to="account.inventory")),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("active_time", models.DurationField()),
                ("waiting_time", models.DurationField()),
                ("steps", models.TextField()),
                ("photo", models.ImageField(upload_to="")),
                ("portions", models.PositiveSmallIntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.profile",
                    ),
                ),
                (
                    "liked_by",
                    models.ManyToManyField(
                        related_name="liked_recipes", to="account.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[("g", "Gram"), ("mL", "Milliliter")], max_length=3
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food.ingredient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ingredient",
            name="recipes",
            field=models.ManyToManyField(to="food.recipe"),
        ),
    ]
