# Generated by Django 4.1.6 on 2023-04-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="active_time",
            field=models.DurationField(
                help_text="The time the recipe takes to make, excluding waiting time."
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="waiting_time",
            field=models.DurationField(
                help_text="The time the recipe takes to make, excluding active time."
            ),
        ),
    ]
